card_control/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()
from views import index

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/$', index),
    url(r'sodexo/', include('sodexo.urls', namespace='sodexo')),
)

sodexo/urls.py
#!/usr/bin/python
# -*- encoding: utf-8 -*-

from django.conf.urls import patterns, url


urlpatterns = patterns(
    'sodexo.views',
    url(r'^restaurant/$', 'restaurant_index', name="restaurant_list"),
    url(r'^restaurant_new/$', 'restaurant_new', name="restaurant_new"),
    url(r'^meal_new/$', 'meal_new'),
    url(r'^meal_list/$', 'meal_index'),
)

sodexo/models.py
from django.db import models
from datetime import date


class Restaurant(models.Model):
    rest_name = models.CharField(verbose_name="name", max_length=100, unique=True)

    def __unicode__(self):
        return "%s" % self.rest_name

    class Meta:
        ordering = ['rest_name']


class Meal(models.Model):
    meal_value = models.DecimalField(verbose_name="value", max_digits=10, decimal_places=2)
    meal_date = models.DateField(verbose_name="date", auto_now_add=True, default=date.today())
    meal_restaurant = models.ForeignKey(
        to=Restaurant, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="restaurant"
    )

    def __unicode__(self):
        return "%s - %s: R$ %s" % (self.meal_date, self.meal_restaurant or '', self.meal_value)

sodexo/forms.py
#!/usr/bin/python
# -*- encoding: utf-8 -*-

from django import forms
from models import Restaurant


class RestaurantForm(forms.Form):
    name = forms.CharField(max_length=100, label="Restaurant")


class MealForm(forms.Form):
    value = forms.DecimalField(decimal_places=2)
    date = forms.DateField()
    restaurant = forms.ModelChoiceField(queryset=Restaurant.objects.all(), label="Restaurant", required=False)

card_control/views.py
#!/usr/bin/python
# -*- encoding: utf-8 -*-

from django.shortcuts import render


def index(request):
    return render(request, 'index.html', {})

sodexo/views.py
from django.shortcuts import render, redirect
from forms import MealForm
from models import Meal
from sodexo.forms import RestaurantForm, Restaurant


# RESTAURANT
def restaurant_index(request):
    restaurants = Restaurant.objects.all()
    return render(request, 'restaurant_index.html', {'object_list': restaurants})


def restaurant_new(request, *args, **kwargs):
    if request.method == 'POST':
        form_restaurant = RestaurantForm(request.POST)
        if form_restaurant.is_valid():
            name = form_restaurant.cleaned_data['name']

            restaurant = Restaurant(rest_name=name)
            restaurant.save()
            return redirect('/sodexo/restaurant')
    else:
        form_restaurant = RestaurantForm()
        return render(request, 'restaurant_new.html', {'object_form': form_restaurant})


# MEALS
def meal_new(request, *args, **kwargs):
    if request.method == 'POST':
        meal_form = MealForm(request.POST)
        if meal_form.is_valid():
            restaurant = meal_form.cleaned_data['restaurant']
            value = meal_form.cleaned_data['value']
            date = meal_form.cleaned_data['date']

            meal = Meal(meal_value=value, meal_date=date, meal_restaurant=restaurant)
            meal.save()
    else:
        meal_form = MealForm()
    return render(request, 'meal_new.html', {'meal_form': meal_form})


def meal_index(request):
    return render(request, 'meal_index.html')

card_control/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block base_title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}bootstrap3/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}bootstrap3/css/bootstrap-theme.min.css">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="{{ STATIC_URL }}bootstrap3/js/bootstrap.min.js"></script>

    <style>
        .white {
            color: #ffffff;
        }
        label {
            color: #ffffff;
        }
        th{
            background-color: deepskyblue;
            color: #000000;
        }
    </style>

</head>
<body style="background-color: #404040;">

{#    <nav class="navbar navbar-inverse" role="navigation">#}
{#    </nav>#}
    <header style="background-color: #000000" class="white">
        <div>
            <span>
                <img src="http://apaics.org/wp-content/uploads/2013/11/Sodexo.png" height="50px" width="150px">
            </span>
        </div>
    </header>

    <div class="container">
        {% block base_messages %}
        {% endblock %}

        {% block base_content %}
        {% endblock %}

        {% block base_footer %}
        {% endblock %}
    </div>



</body>
</html>

card_control/templates/index.html
{% extends 'base.html' %}

{% block base_title %}
    Card Control
{% endblock %}

{% block base_content %}
{% endblock %}

sodexo/templates/meal_index.html
{% extends 'base.html' %}

{% block base_content %}
    <h1 class="text-center">Listing Meals</h1>
    <table class="table table-hover table-condensed">
        <thead>
            <tr>
                <th>Restaurant</th>
                <th>Date</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Rei Davi</td>
                <td>2014-02-10</td>
                <td>13.65</td>
            </tr>
            <tr>
                <td>Rei Davi</td>
                <td>2014-02-10</td>
                <td>13.65</td>
            </tr>
            <tr>
                <td>Rei Davi</td>
                <td>2014-02-10</td>
                <td>13.65</td>
            </tr>
        </tbody>
    </table>
{% endblock %}

sodexo/templates/meal_new.html
{% extends 'base.html' %}

{% block base_messages %}
    {% if meal_form.errors %}
        <p style="color: red;">
            Please correct the error{{ meal_form.errors|pluralize }} below.
        {{ meal_form.errors }}
        </p>
    {% endif %}
{% endblock %}

{% block base_content %}
    <form method="post" class="form-horizontal" role="form" action="">
        {% csrf_token %}
        <h1 class="text-center white">New Meal</h1>
        <br/>
        <table>
            {{ meal_form.as_table }}
        </table>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
                <button type="submit" class="btn btn-info">Create and New</button>
            </div>
        </div>
    </form>
    <button type="button" class="btn btn-default">Back</button>
{% endblock %}

sodexo/templates/restaurant_index.html
{% extends 'base.html' %}

{% block base_content %}
    <aside>
        <nav>
            <ul>
                <li>1</li>
                <li>1</li>
                <li>1</li>
                <li>1</li>
            </ul>
        </nav>
    </aside>
    <div>
        <a href="{% url 'sodexo:restaurant_new' %}" class="btn btn-primary">
            New Restaurant
        </a>
    </div>
    <div>
        <table class="white table table-bordered table-condensed">
            <caption><h2>Listing Restaurants</h2></caption>
            <thead>
            <tr>
                <th>Name</th>
            </tr>
            </thead>
            <tbody>
            {% for each_restaurant in object_list %}
                <tr>
                    <td>{{ each_restaurant.rest_name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

sodexo/templates/restaurant_new.html
{% extends 'base.html' %}

{% block base_content %}
    <form class="form-horizontal" role="form" action="" method="post">
        {% csrf_token %}
        <h1 class="text-center white">New Restaurant</h1>
{#        {{ object_form.as_p }}#}

        <div class="form-group">
            <label for="{{ object_form.name.id_for_label }}" class="control-label col-sm-2">
                {{ object_form.name.label }}:
            </label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="{{ object_form.name.id_for_label }}"
                       name="{{ object_form.name.name }}">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
                <button type="submit" class="btn btn-info">Create and New</button>
            </div>
        </div>



    </form>
    <a href="{% url 'sodexo:restaurant_list' %}" class="btn btn-default">Back</a>
{% endblock %}